services:
  postgres:
    image: postgres:16-alpine
    container_name: missionary-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: missionary_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/pg_hba.conf:ro
    command: ['postgres', '-c', 'hba_file=/etc/pg_hba.conf']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
